# Dockerfile

# Use an official Python runtime as a base image
FROM python:3.11-alpine

# Command to generate and print the Django secret key
CMD python -c "import secrets; print('SECRET_KEY=' + secrets.token_urlsafe())"